name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write # Required for creating tags and releases
  id-token: write # Required for NPM provenance

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile || {
            echo "Frozen lockfile failed"
          }

      - name: Build
        run: pnpm run build

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

  check-version:
    name: Check for Version Change
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      version_changed: ${{ steps.version-check.outputs.version_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history to compare versions

      - name: Check if version changed
        id: version-check
        run: |
          if git diff HEAD~1 package.json | grep -q '"version"'; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "New version detected in package.json"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "No version change detected"
          fi

  publish:
    name: Publish to NPM
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    uses: ./.github/workflows/npm-publish.yml
    with:
      use_trusted_publishing: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}